---
# mysql install
- name: check mysql has already installed
  shell: which mysql
  register: which_mysql
  failed_when: which_mysql.rc not in [0, 1]

- name: download mysql 5.6
  shell: yum -y install http://dev.mysql.com/get/mysql-community-release-el6-5.noarch.rpm
  when: which_mysql.rc == 1

- name: install mysql 5.6
  shell: yum -y install mysql-community-server
  when: which_mysql.rc == 1

- name: install mysql relational packages
  yum: name={{ item }} state=installed
  with_items:
    - mysql-devel
    - MySQL-python

- name: run mysqld
  service: name=mysqld state=running enabled=yes

# mysql setting
# - name: set up mysql_secure_installation
#   shell: /usr/bin/mysql_secure_installation

- name: create app write users
  mysql_user:
    name={{ db_user.write_user.name }}
    password={{ db_user.write_user.password }}
    priv=*.*:ALL
    state=present

- name: create app read users
  mysql_user:
    name={{ db_user.read_user.name }}
    password={{ db_user.read_user.password }}
    priv=*.*:SELECT
    state=present

- name: set my.conf to db server
  template: src=./../files/my.cnf dest=/etc/my.cnf owner=root mode=0644
  register: my_conf

- name: restart mysql
  service: name=mysqld state=restarted
  when: my_conf.changed
