---
- name: Check if selinux is installed
  command: getenforce
  register: command_result
  ignore_errors: True

- name: Install libselinux-python
  yum: name={{ item }}
  with_items: 
    - epel-release
    - libselinux-python
  when: command_result|success and command_result.stdout != 'Disabled'

- name: install ruby
  yum: name=ruby state=absent
 
- name: check out rbenv
  git: repo={{ rbenv.repo }} dest=~/.rbenv accept_hostkey=yes
  sudo: no

- name: check out rbenv
  shell: echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bash_profile
  sudo: no

- name: check out rbenv
  shell: echo 'eval "$(rbenv init -)"' >> ~/.bash_profile
  sudo: no

- name: checkout ruby-build as rbenv plugin
  git: repo={{ rubybuild.repo }} dest=~/.rbenv/plugins/ruby-build accept_hostkey=yes
  sudo: no
 
- name: install ruby-build
  shell: /home/{{ user }}/.rbenv/plugins/ruby-build/install.sh
 
- name: check whether a specific version of ruby is installed or not
  shell: ~/.rbenv/bin/rbenv versions | grep {{ ruby.version }} | tr '*' ' ' | sed -e 's/\s\+//' | cut -f1 -d' '
  register: rbenv_version
  sudo: no
 
- name: install ruby with rbenv
  command: ~/.rbenv/bin/rbenv install {{ ruby.version }}
  when: rbenv_version.stdout != "{{ ruby.version }}"
  sudo: no
 
- name: set ruby version global
  command: ~/.rbenv/bin/rbenv global {{ ruby.version }}
  sudo: no
 
- name: update gems
  command: ~/.rbenv/bin/rbenv exec gem update --system
  sudo: no
 
- name: install bundler gem
  command: ~/.rbenv/bin/rbenv exec gem install bundler --no-ri --no-rdoc
  sudo: no
 
- name: rbenv rehash
  command: ~/.rbenv/bin/rbenv rehash
  sudo: no

- name: install libxslt2-devel
  shell: yum -y install libxml2 libxslt libxml2-devel libxslt-devel

- name: install nokogiri
  command: ~/.rbenv/bin/rbenv exec gem install nokogiri -- --use-system-libraries
  sudo: no

- name: for nokogiri
  command: ~/.rbenv/bin/rbenv exec gem install --no-ri --no-rdoc rails
  sudo: no

- name: install rails
  command: ~/.rbenv/bin/rbenv exec gem install rails
  sudo: no

- name: rbenv rehash
  command: ~/.rbenv/bin/rbenv rehash
  sudo: no