" vim の独自拡張機能を使う(viとの互換性をとらない)
set nocompatible
" マウス機能有効化
set mouse=a
" 文字コードを指定する
set encoding=utf8
set fenc=utf-8
" ファイルエンコードを指定する
set fileencodings=iso-2022-jp,euc-jp,sjis,utf-8
" 自動認識させる改行コードを指定する
set fileformats=unix,dos
" 検索履歴を50個残す
set history=50
" 検索時に大文字小文字を区別しない
set ignorecase
" 検索語に大文字を混ぜると検索時に大文字を区別する
set smartcase
" 検索語にマッチした単語をハイライトする
set hlsearch
" インクリメンタルサーチを使う ( 検索語を入れている途中から随時マッチする文字列の検索を開始)
set incsearch
" 改行 ( $ ) やタブ ( ^I ) を可視化する
" set list
" インデントをTabではなくスペース4つで揃える　
set tabstop=4
set autoindent
set expandtab
set shiftwidth=4
" 括弧入力時に対応する括弧を強調する
set showmatch
" 構文ごとに色分け表示する
syntax on

" highlight Comment ctermfg=LightCyan
" ウィンドウ幅で行を折り返す
set wrap
" ステータスラインを常に表示
set laststatus=2
" ステータスラインの内容
set statusline=%F%r%h%=
