---
# install necessary modules
- name: install git
  yum: name=git state=present

- name: install epel
  yum: name=epel-release state=present

- name: install necessary modules
  yum: name={{ item }} state=present
  with_items:
    - libselinux-python
    - vim-enhanced

# add application user
- name: add application group
  group: name={{ user.name }} state=present

- name: add application user
  user:
    name={{ user.name }}
    password={{ user.password }}
    group={{ user.name }}
    home=/home/{{ user.name }}
    state=present

- name: register application user to sudoers
  lineinfile: >-
    dest='/etc/sudoers'
    backup=yes
    state=present
    regexp='^"{{ user.name }}"'
    line='"{{ user.name }}" ALL=(ALL) NOPASSWD: ALL'

- name: register public key
  # ローカルマシンのpublick keyを作成したユーザーに配布
  # TODO: stateとproductionの時、秘密鍵公開鍵を共有するか。
  authorized_key: user={{ user.name }} key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

# set vimrc
- name: check vimrc exist.
  stat: path=/home/{{ user.name }}/.vimrc
  register: vimrc_file

- name: set my.conf to db server
  template: src=./../files/vimrc dest=/home/{{ user.name }}/.vimrc owner={{ user.name }} mode=0644
  when: vimrc_file.stat.md5 is not defined

- name: check out rbenv
  shell: echo 'alias vi="vim"' >> /home/{{ user.name }}/.bash_profile
  when: vimrc_file.stat.md5 is not defined
