---
# install necessary modules
- name: install git
  yum: name=git state=present

- name: install epel
  yum: name=epel-release state=present

- name: install necessary modules
  yum: name={{ item }} state=present
  with_items:
    - libselinux-python

# add application user
- name: add application group
  group: name={{ user.name }} state=present

- name: add application user
  user:
    name={{ user.name }}
    password={{ user.password }}
    group={{ user.name }}
    home=/home/{{ user.name }}
    state=present

- name: register application user to sudoers
  lineinfile: >-
    dest='/etc/sudoers'
    backup=yes
    state=present
    regexp='^"{{ user.name }}"'
    line='"{{ user.name }}" ALL=(ALL) NOPASSWD: ALL'

- name: register public key
  # ローカルマシンのpublick keyを作成したユーザーに配布
  # TODO: stateとproductionの時、秘密鍵公開鍵を共有するか。
  authorized_key: user={{ user.name }} key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
