---
# install necessary modules
- name: install git
  yum: name=git state=present

- name: install epel
  yum: name=epel-release state=present

- name: install node.js
  yum: name=nodejs state=present

- name: install npm
  yum: name=npm state=present

- name: install ImageMagick
  yum: name=ImageMagick state=present