---
# install rbenv
- name: check app has checked out.
  stat: path={{ app.dir }}
  register: app_dir
  sudo: no

- name: check out app
  git: repo={{ app.repo }} dest={{ app.dir }} accept_hostkey=yes
  when: app_dir.stat.exists == False or app_dir.stat.isdir == False
  sudo: no

#- name: create app synbolic link
#  file: >
#    src={{ app.src }}
#    dest={{ app.dest }}
#    mode=0755
#    state=link
#  when: app_dir.stat.exists == False or app_dir.stat.isdir == False
#  sudo: no
