- hosts: server
  remote_user: bang
  sudo: yes
  vars:
    httpd_port: 80
    rbenv:
      repo: git://github.com/sstephenson/rbenv.git
    rubybuild:
      repo: git://github.com/sstephenson/ruby-build.git
    ruby:
      version: 2.1.5
  roles:
    - webserver
    - ruby
